/*
 * Name: Ildar Nasirov
 * Project Name: Spend and Go
 * Version: 0.5
 * NITV:  - Transaction list self finally manages
 ************************************************************************
 * ToDo:  - add the quick-select option
 *        - add the functionality of the daily budget management
 ************************************************************************
 */
package spend.and.go;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Ildar
 */
public class UI_Master extends javax.swing.JFrame {

    /**
     * Variable Declarations
     */
    public static File file = new File("C:\\Users\\ildar\\OneDrive\\Documents\\NetBeansProjects\\Tests\\SpendAndGo.txt");
    public static File transactions = new File("C:\\Users\\ildar\\OneDrive\\Documents\\NetBeansProjects\\Tests\\Transactions.txt");
    private double mealPlanAmt = -1;
    private double flexAmt = -1;
    private int daysAmt = -1;
    private boolean combine = false;
    ArrayList<String> neededInfo = new ArrayList();
    TransactionsQueue transactionsList = new TransactionsQueue(10);
    double priceMain = -1;
    double balanceMain = -1;

    public UI_Master() {

        initComponents();
        setup();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SpendAndGo = new javax.swing.JTabbedPane();
        Main = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        BalanceMain = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Option1Main = new javax.swing.JButton();
        Option2Main = new javax.swing.JButton();
        Option3Main = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        LimitMain = new javax.swing.JProgressBar();
        jLabel18 = new javax.swing.JLabel();
        NamePrice = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        PriceMain = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        ConfirmMain = new javax.swing.JButton();
        PastTransactions = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        FlexMain = new javax.swing.JLabel();
        Splash = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        IncludeConfirm = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ConfirmSplash = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        MealPlanAmt = new javax.swing.JTextField();
        FlexAmt = new javax.swing.JTextField();
        DaysAmt = new javax.swing.JTextField();
        Updater = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Option1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        NameQ1 = new javax.swing.JFormattedTextField();
        PriceQ1 = new javax.swing.JFormattedTextField();
        Option2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NameQ2 = new javax.swing.JFormattedTextField();
        PriceQ2 = new javax.swing.JFormattedTextField();
        Option3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        NameQ3 = new javax.swing.JFormattedTextField();
        PriceQ3 = new javax.swing.JFormattedTextField();
        ConfirmUpdater = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        FlexAmtUpdater = new javax.swing.JTextField();
        MPDAmtUpdater = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel5.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel5.setText("Spend and Go");

        jLabel15.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel15.setText("Available Balance:");

        BalanceMain.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        BalanceMain.setText("$0.00");

        jLabel17.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel17.setText("   Quick Select Options");

        Option1Main.setText("Option 1");

        Option2Main.setText("Option 2");

        Option3Main.setText("Option 3");
        Option3Main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Option3MainActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel16.setText("      Non-Quick Select");

        LimitMain.setForeground(new java.awt.Color(204, 204, 204));
        LimitMain.setToolTipText("");
        LimitMain.setValue(55);

        jLabel18.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel18.setText("Name:");

        NamePrice.setText("Please Enter a Name");
        NamePrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NamePriceMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                NamePriceMouseExited(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel19.setText("Price:");

        PriceMain.setText("Please Enter a Value");
        PriceMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PriceMainMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PriceMainMouseExited(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel20.setText("Your daily limit:");

        ConfirmMain.setText("Confirm");
        ConfirmMain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmMainActionPerformed(evt);
            }
        });

        PastTransactions.setText("Show Past Transactions");
        PastTransactions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PastTransactionsActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel23.setText("Flex Balance:");

        FlexMain.setText("$0.00");

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(MainLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(PriceMain))
                            .addComponent(NamePrice, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(MainLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BalanceMain)
                                .addGap(18, 18, 18)
                                .addComponent(PastTransactions))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                                        .addGap(137, 137, 137)
                                        .addComponent(ConfirmMain))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MainLayout.createSequentialGroup()
                                        .addComponent(Option1Main)
                                        .addGap(67, 67, 67)
                                        .addComponent(Option2Main)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(34, 34, 34))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainLayout.createSequentialGroup()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(LimitMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FlexMain)
                    .addComponent(jLabel23)
                    .addComponent(Option3Main))
                .addGap(45, 45, 45))
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(16, 16, 16)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(BalanceMain))
                    .addComponent(PastTransactions, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Option2Main)
                    .addComponent(Option1Main)
                    .addComponent(Option3Main))
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(NamePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(PriceMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmMain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(5, 5, 5)
                        .addComponent(LimitMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MainLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FlexMain))))
        );

        SpendAndGo.addTab("Main Page", Main);

        jLabel21.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel21.setText("Meal Plan Budget: Splash Screen");

        jLabel22.setText("Would You Like to Include Your Flex Dollars in the Budget?");

        IncludeConfirm.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        IncludeConfirm.setText("Yes, Please");
        IncludeConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncludeConfirmActionPerformed(evt);
            }
        });

        jLabel24.setText("Please Enter Your Starting Balances and");

        jLabel25.setText("Amount of Days Left in a Semester.");

        jLabel26.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel26.setText("Meal Plan Dollars Amount");

        jLabel27.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel27.setText("Flex Dollars Amount");

        ConfirmSplash.setText("Confirm");
        ConfirmSplash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmSplashActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel28.setText("Number of Days in Semester");

        MealPlanAmt.setColumns(16);
        MealPlanAmt.setText("Please Enter a Numerical Value");
        MealPlanAmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MealPlanAmtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MealPlanAmtMouseExited(evt);
            }
        });
        MealPlanAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MealPlanAmtActionPerformed(evt);
            }
        });

        FlexAmt.setColumns(16);
        FlexAmt.setText("Please Enter a Numercial Value");
        FlexAmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FlexAmtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                FlexAmtMouseExited(evt);
            }
        });
        FlexAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlexAmtActionPerformed(evt);
            }
        });

        DaysAmt.setColumns(16);
        DaysAmt.setText("Please Enter a Numerical Value");
        DaysAmt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DaysAmtMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DaysAmtMouseExited(evt);
            }
        });
        DaysAmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaysAmtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SplashLayout = new javax.swing.GroupLayout(Splash);
        Splash.setLayout(SplashLayout);
        SplashLayout.setHorizontalGroup(
            SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel24)
                .addGap(86, 86, 86))
            .addGroup(SplashLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(44, 44, 44))
            .addGroup(SplashLayout.createSequentialGroup()
                .addGroup(SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SplashLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(MealPlanAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(FlexAmt, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                    .addGroup(SplashLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel21)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(99, 99, 99))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(132, 132, 132))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(IncludeConfirm)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(ConfirmSplash)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SplashLayout.createSequentialGroup()
                        .addComponent(DaysAmt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(111, 111, 111))))
        );
        SplashLayout.setVerticalGroup(
            SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SplashLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IncludeConfirm)
                .addGap(18, 18, 18)
                .addComponent(jLabel24)
                .addGap(0, 0, 0)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addGroup(SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MealPlanAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlexAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel28)
                .addGap(3, 3, 3)
                .addComponent(DaysAmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmSplash)
                .addGap(18, 18, 18))
        );

        jLabel27.setVisible(false);
        FlexAmt.setVisible(false);

        SpendAndGo.addTab("Splash Screen", Splash);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        jLabel1.setText("Please Update Your Information");

        jLabel6.setText("Option 1");

        jLabel7.setText("Price: ");

        jLabel8.setText("Name: ");

        NameQ1.setText("Please Enter The Name of the Product");

        PriceQ1.setText("Please Enter The Price");
        PriceQ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PriceQ1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Option1Layout = new javax.swing.GroupLayout(Option1);
        Option1.setLayout(Option1Layout);
        Option1Layout.setHorizontalGroup(
            Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PriceQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameQ1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Option1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(163, 163, 163))
        );
        Option1Layout.setVerticalGroup(
            Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option1Layout.createSequentialGroup()
                .addComponent(jLabel6)
                .addGap(26, 26, 26)
                .addGroup(Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(NameQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Option1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PriceQ1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Option 1", Option1);

        jLabel9.setText("Option 2");

        jLabel10.setText("Name: ");

        jLabel11.setText("Price:");

        NameQ2.setText("Please Enter The Name of the Product");

        PriceQ2.setText("Please Enter The Price");

        javax.swing.GroupLayout Option2Layout = new javax.swing.GroupLayout(Option2);
        Option2.setLayout(Option2Layout);
        Option2Layout.setHorizontalGroup(
            Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceQ2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Option2Layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(163, 163, 163))
        );
        Option2Layout.setVerticalGroup(
            Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(26, 26, 26)
                .addGroup(Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(NameQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Option2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceQ2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Option 2", Option2);

        jLabel12.setText("Option 3");

        jLabel13.setText("Name: ");

        jLabel14.setText("Price: ");

        NameQ3.setText("Please Enter The Name of the Product");

        PriceQ3.setText("Please Enter The Price");

        javax.swing.GroupLayout Option3Layout = new javax.swing.GroupLayout(Option3);
        Option3.setLayout(Option3Layout);
        Option3Layout.setHorizontalGroup(
            Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Option3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(5, 5, 5))
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PriceQ3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Option3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(163, 163, 163))
        );
        Option3Layout.setVerticalGroup(
            Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Option3Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addGap(26, 26, 26)
                .addGroup(Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(Option3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PriceQ3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Option 3", Option3);

        ConfirmUpdater.setText("Confirm");
        ConfirmUpdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmUpdaterActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Flex Dollars Amount");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel3.setText("Meal Plan Dollars Amount");

        FlexAmtUpdater.setText("Please Enter a Value");
        FlexAmtUpdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlexAmtUpdaterActionPerformed(evt);
            }
        });

        MPDAmtUpdater.setText("Please Enter a Value");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setText("Quick Select Option");

        javax.swing.GroupLayout UpdaterLayout = new javax.swing.GroupLayout(Updater);
        Updater.setLayout(UpdaterLayout);
        UpdaterLayout.setHorizontalGroup(
            UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdaterLayout.createSequentialGroup()
                .addGroup(UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UpdaterLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdaterLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UpdaterLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3))
                            .addGroup(UpdaterLayout.createSequentialGroup()
                                .addComponent(FlexAmtUpdater, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MPDAmtUpdater, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(UpdaterLayout.createSequentialGroup()
                        .addGroup(UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UpdaterLayout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel4))
                            .addGroup(UpdaterLayout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(UpdaterLayout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(ConfirmUpdater)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UpdaterLayout.setVerticalGroup(
            UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UpdaterLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(UpdaterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MPDAmtUpdater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FlexAmtUpdater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(5, 5, 5)
                .addComponent(jTabbedPane1)
                .addGap(26, 26, 26)
                .addComponent(ConfirmUpdater)
                .addGap(122, 122, 122))
        );

        SpendAndGo.addTab("Updater", Updater);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SpendAndGo)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SpendAndGo, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void PriceQ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PriceQ1ActionPerformed
    }//GEN-LAST:event_PriceQ1ActionPerformed
    private void FlexAmtUpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlexAmtUpdaterActionPerformed
    }//GEN-LAST:event_FlexAmtUpdaterActionPerformed
    private void ConfirmUpdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmUpdaterActionPerformed
    }//GEN-LAST:event_ConfirmUpdaterActionPerformed
    private void Option3MainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Option3MainActionPerformed
    }//GEN-LAST:event_Option3MainActionPerformed
    private void ConfirmMainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmMainActionPerformed
        if (priceMain == -1 || NamePrice.getText().equals("Please Enter a Name")
                || priceMain > balanceMain) {
            JOptionPane.showMessageDialog(null, "Sorry, it seems that "
                    + "your input is invalid, or insufficient funds",
                    "Error", JOptionPane.PLAIN_MESSAGE);
        } else {

            try {
                if (transactionsList.isFull()) {
                    transactionsList.dequeue();
                }
                transactionsList.enqueue("$ " + priceMain + " ---- " + NamePrice.getText());
                PriceMain.setText("Please Enter a Value");
                NamePrice.setText("Please Enter a Name");
                if (!combine) {
                    mealPlanAmt = mealPlanAmt - priceMain;
                    balanceMain = balanceMain - priceMain;
                    toWrite(Boolean.toString(combine) + "\n" + mealPlanAmt + "\n" + daysAmt);
                } else {
                    System.out.println(priceMain);
                    if (priceMain >= mealPlanAmt) {
                        priceMain = priceMain - mealPlanAmt;
                        flexAmt = flexAmt - priceMain;
                        mealPlanAmt = 0;
                    } else {
                        mealPlanAmt = mealPlanAmt - priceMain;
                    }
                    balanceMain = mealPlanAmt + flexAmt;
                    FlexMain.setText("$" + new DecimalFormat("##.00").format(flexAmt));
                    toWrite(Boolean.toString(combine) + "\n" + mealPlanAmt + "\n" + flexAmt + "\n" + daysAmt);
                }
                BalanceMain.setText("$" + new DecimalFormat("##.00").format(balanceMain));
                priceMain = -1;

            } catch (Exception e) {
                Logger.getLogger(UI_Master.class.getName()).log(Level.SEVERE, null, e);
            }
        }


    }//GEN-LAST:event_ConfirmMainActionPerformed
    private void PastTransactionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PastTransactionsActionPerformed
        JOptionPane.showMessageDialog(null, transactionsList.toString(), "Transactions", JOptionPane.PLAIN_MESSAGE);
        try {
            toWriteQueue(transactionsList.toString());
        } catch (Exception e) {

        }
    }//GEN-LAST:event_PastTransactionsActionPerformed
    private void IncludeConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncludeConfirmActionPerformed
        try {
            if (IncludeConfirm.isSelected()) {
                jLabel27.setVisible(true);
                FlexAmt.setVisible(true);
                combine = true;
            } else {
                jLabel27.setVisible(false);
                FlexAmt.setVisible(false);
                FlexAmt.setText("Please Enter a Numerical Value");
                combine = false;
            }
        } catch (Exception ex) {
            Logger.getLogger(UI_Master.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IncludeConfirmActionPerformed
    private void ConfirmSplashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmSplashActionPerformed
        if (combine) {
            if (flexAmt == -1 || daysAmt == -1 || mealPlanAmt == -1) {
                JOptionPane.showMessageDialog(null, "Please fill out information", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    toWrite("true" + "\n" + mealPlanAmt + "\n" + flexAmt + "\n" + daysAmt);
                    toWriteQueue("");
                    setup();
                } catch (Exception ex) {
                    Logger.getLogger(UI_Master.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (daysAmt == -1 || mealPlanAmt == -1) {
                JOptionPane.showMessageDialog(null, "Please Fill Out Your Information Before Proceeding", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                try {
                    toWrite("false" + "\n" + mealPlanAmt + "\n" + daysAmt);
                    toWriteQueue("");
                    setup();
                } catch (Exception ex) {
                    Logger.getLogger(UI_Master.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_ConfirmSplashActionPerformed
    private void FlexAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlexAmtActionPerformed
    }//GEN-LAST:event_FlexAmtActionPerformed
    private void MealPlanAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MealPlanAmtActionPerformed
    }//GEN-LAST:event_MealPlanAmtActionPerformed
    private void MealPlanAmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealPlanAmtMouseClicked
        MealPlanAmt.setText("");
    }//GEN-LAST:event_MealPlanAmtMouseClicked
    private void MealPlanAmtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MealPlanAmtMouseExited
        try {
            mealPlanAmt = Double.parseDouble(MealPlanAmt.getText());
            if (mealPlanAmt > 9999 || mealPlanAmt < 0) {
                JOptionPane.showMessageDialog(null, "Unrealistic or Invalid Number", "Error", JOptionPane.ERROR_MESSAGE);
                MealPlanAmt.setText("Please Enter a Numerical Value");
                mealPlanAmt = -1;
            }
            MealPlanAmt.setText(new DecimalFormat("##.00").format(mealPlanAmt));
        } catch (NumberFormatException ex) {
            MealPlanAmt.setText("Please Enter a Numerical Value");
            mealPlanAmt = -1;
        } catch (Exception ex) {
            Logger.getLogger(UI_Master.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            jLabel21.grabFocus();
        };
    }//GEN-LAST:event_MealPlanAmtMouseExited

    private void FlexAmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlexAmtMouseClicked
        FlexAmt.setText("");
    }//GEN-LAST:event_FlexAmtMouseClicked

    private void FlexAmtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FlexAmtMouseExited
        try {
            flexAmt = Double.parseDouble(FlexAmt.getText());
            if (flexAmt > 9999 || flexAmt < 0) {
                JOptionPane.showMessageDialog(null, "Unrealistic or Invalid Number", "Error", JOptionPane.ERROR_MESSAGE);
                FlexAmt.setText("Please Enter a Numerical Value");
                flexAmt = -1;
            }
            FlexAmt.setText(new DecimalFormat("##.00").format(flexAmt));
        } catch (NumberFormatException ex) {
            FlexAmt.setText("Please Enter a Numerical Value");
            flexAmt = -1;
        } catch (Exception ex) {
            Logger.getLogger(UI_Master.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            jLabel21.grabFocus();
        };
    }//GEN-LAST:event_FlexAmtMouseExited

    private void DaysAmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaysAmtActionPerformed
    }//GEN-LAST:event_DaysAmtActionPerformed

    private void DaysAmtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaysAmtMouseClicked
        DaysAmt.setText("");
    }//GEN-LAST:event_DaysAmtMouseClicked

    @SuppressWarnings("empty-statement")
    private void DaysAmtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DaysAmtMouseExited
        try {
            daysAmt = Integer.parseInt(DaysAmt.getText());
            if (daysAmt > 9999 || daysAmt < 0) {
                JOptionPane.showMessageDialog(null, "Unrealistic or Invalid Number", "Error", JOptionPane.ERROR_MESSAGE);
                DaysAmt.setText("Please Enter a Numerical Value");
                daysAmt = -1;
            }
        } catch (NumberFormatException ex) {
            DaysAmt.setText("Please Enter a Numerical Value");
            daysAmt = -1;
        } catch (Exception ex) {
            Logger.getLogger(UI_Master.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            jLabel21.grabFocus();
        };
    }//GEN-LAST:event_DaysAmtMouseExited

    private void PriceMainMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriceMainMouseExited
        try {
            priceMain = Double.parseDouble(PriceMain.getText());
            if (priceMain > 9999 || priceMain < 0) {
                JOptionPane.showMessageDialog(null, "Unrealistic or Invalid Number", "Error", JOptionPane.ERROR_MESSAGE);
                PriceMain.setText("Please Enter a Value");
                priceMain = -1;
            }
            PriceMain.setText(new DecimalFormat("##.00").format(priceMain));
        } catch (NumberFormatException ex) {
            PriceMain.setText("Please Enter a Value");
            priceMain = -1;
        } catch (Exception ex) {
            Logger.getLogger(UI_Master.class
                    .getName()).log(Level.SEVERE, null, ex);
        } finally {
            jLabel5.grabFocus();
        };
    }//GEN-LAST:event_PriceMainMouseExited

    private void PriceMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PriceMainMouseClicked
        PriceMain.setText("");
    }//GEN-LAST:event_PriceMainMouseClicked

    private void NamePriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamePriceMouseClicked
        NamePrice.setText("");
    }//GEN-LAST:event_NamePriceMouseClicked

    private void NamePriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NamePriceMouseExited
        if (NamePrice.getText().equals("")) {
            NamePrice.setText("Please Enter a Name");
        }
    }//GEN-LAST:event_NamePriceMouseExited

    /**
     * @param args the command line arguments
     * @throws java.io.FileNotFoundException
     */
    public static void main(String args[]) throws FileNotFoundException {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_Master.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_Master.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_Master.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_Master.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_Master().setVisible(true);
            }
        }
        );
    }

    private void setup() {
        if (file.exists()) {

            SpendAndGo.setEnabledAt(0, true);
            SpendAndGo.setEnabledAt(2, true);
            SpendAndGo.remove(Splash);

            try {
                toRead();
                toReadQueue();
                mealPlanAmt = Double.parseDouble(neededInfo.get(1));
                if (neededInfo.get(0).equalsIgnoreCase("false")) {
                    combine = false;
                    flexAmt = 0;
                    daysAmt = Integer.parseInt(neededInfo.get(2));
                    balanceMain = mealPlanAmt;
                    BalanceMain.setText("$" + new DecimalFormat("##.00").format(balanceMain));

                    FlexMain.setVisible(false);
                    jLabel23.setVisible(false);
                    FlexMain.setVisible(false);
                    jLabel23.setVisible(false);
                } else {
                    combine = true;
                    flexAmt = Double.parseDouble(neededInfo.get(2));
                    daysAmt = Integer.parseInt(neededInfo.get(3));
                    balanceMain = mealPlanAmt + flexAmt;
                    BalanceMain.setText("$ " + new DecimalFormat("##.00").format(balanceMain));
                    FlexMain.setText("$ " + new DecimalFormat("##.00").format(flexAmt));
                }
            } catch (Exception e) {
                System.out.println("The file does not exist");
            }
        } else {
            SpendAndGo.setSelectedComponent(Splash);
            SpendAndGo.setEnabledAt(0, false);
            SpendAndGo.setEnabledAt(2, false);
        }
    }

    private static void toWrite(String info) throws Exception {
        FileWriter fw = new FileWriter(file);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(info);
        bw.close();
    }

    private void toReadQueue() throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(transactions);
        BufferedReader br = new BufferedReader(fr);
        String line = br.readLine();
        while (line != null) {
            transactionsList.enqueue(line);
            line = br.readLine();
        }
        br.close();
    }

    private void toWriteQueue(String line) throws IOException {
        FileWriter fw = new FileWriter(transactions);
        BufferedWriter bw = new BufferedWriter(fw);
        bw.write(line);
        bw.close();

    }

    private void toRead() throws FileNotFoundException, IOException {
        FileReader fr = new FileReader(file);
        BufferedReader br = new BufferedReader(fr);
        String line = br.readLine();
        while (line != null) {
            neededInfo.add(line);
            line = br.readLine();
        }
        br.close();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalanceMain;
    private javax.swing.JButton ConfirmMain;
    private javax.swing.JButton ConfirmSplash;
    private javax.swing.JButton ConfirmUpdater;
    private javax.swing.JTextField DaysAmt;
    private javax.swing.JTextField FlexAmt;
    private javax.swing.JTextField FlexAmtUpdater;
    private javax.swing.JLabel FlexMain;
    private javax.swing.JCheckBox IncludeConfirm;
    private javax.swing.JProgressBar LimitMain;
    private javax.swing.JTextField MPDAmtUpdater;
    private javax.swing.JPanel Main;
    private javax.swing.JTextField MealPlanAmt;
    private javax.swing.JTextField NamePrice;
    private javax.swing.JFormattedTextField NameQ1;
    private javax.swing.JFormattedTextField NameQ2;
    private javax.swing.JFormattedTextField NameQ3;
    private javax.swing.JPanel Option1;
    private javax.swing.JButton Option1Main;
    private javax.swing.JPanel Option2;
    private javax.swing.JButton Option2Main;
    private javax.swing.JPanel Option3;
    private javax.swing.JButton Option3Main;
    private javax.swing.JButton PastTransactions;
    private javax.swing.JTextField PriceMain;
    private javax.swing.JFormattedTextField PriceQ1;
    private javax.swing.JFormattedTextField PriceQ2;
    private javax.swing.JFormattedTextField PriceQ3;
    private javax.swing.JTabbedPane SpendAndGo;
    private javax.swing.JPanel Splash;
    private javax.swing.JPanel Updater;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
